### ISSUE TITLE
Network requirements?

### ISSUE THREAD

**Issue by GamePlayer-8** [Rexxt/ticlock#3]
For what is the `apps/splatoon3.ink.py` file for?

**Comment by Rexxt** [comment]
https://splatoon3.ink/

**Comment by GamePlayer-8** [comment]
Why it's implemented inside clock?

**Comment by Rexxt** [comment]
because it's a standard program

**Comment by GamePlayer-8** [comment]
Closing issue then.

Related to https://github.com/Rexxt/ticlock/pull/2#issuecomment-1529613275
